name: "Build Deploy Docker Image"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Docker Image"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: cd docker/deploy/dev && docker build -t xacc/xacc . --no-cache
      
    