name: "Linux CI"

on:
  push:
    branches: [ master, xacc-devel ]
  pull_request:
    branches: [ master ]
  schedule:
    # once every weekend
    - cron: '0 3 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Linux CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory build
      
      - name: Install dependencies
        run: sudo apt-get -y update && sudo apt-get install -y --no-install-recommends ninja-build libssl-dev python3 libpython3-dev python3-pip libblas-dev liblapack-dev
      
      - name: Configure
        working-directory: build/
        run: cmake -GNinja $GITHUB_WORKSPACE -DXACC_BUILD_TESTS=TRUE -DXACC_BUILD_EXAMPLES=TRUE
    
      - name: Build
        working-directory: build/
        run: cmake --build . --target install
      
      - name: Test
        working-directory: build/
        run: ctest --output-on-failure